config/routes.rb
Wikiscrape::Application.routes.draw do
  resources :documents

  resources :links

  resources :cats

  match "/topics/get/:name" => "topics#get"
  match "/cats/get/:name" => "cats#get"
  match "/multiple/:name" => "topics#multiple_choice"
  match "/topics/index"
  match "/cats/index" => "cats#index"
  match "topics/test/:name" => "topics#test"
  match "topics/get_topic" => "topics#get_topic"
  match "/cat_lookup/:name" => "lists#category_lookup"
  match "/to_csv/:id/:file_name" => "documents#export_document_to_csv"
  match "/documents/disambiguate_term" => "documents#disambiguate_term"
  match "/documents/reload_term" => "documents#reload_term"
  match "/documents/show" => "documents#show"
  match "/documents/:id" => "documents#show"

  resources :terms
  resources :topics

  root :to => "documents#index"

end

app/models/document.rb
class Document < ActiveRecord::Base
  has_and_belongs_to_many :topic_identifiers

  def self.test_iconv(str)
    test = Iconv.conv("UTF-8//IGNORE", "US-ASCII", str)
    return test
  end

  def self.parse_list(id)
    @document = Document.find_by_id(id)
    @topic_identifiers = @document.csv.split /(?:\n|\r)+/
    @ambiguous_terms = []
    @topic_identifiers.each do |ti|
      #check if the topic_identifier exists already
      @topic_identifier = TopicIdentifier.find_by_name(ti)

      if @topic_identifier.nil?
        #check topic_identifier for wiki article
        topic_name = Topic.wiki_page_name(ti)

        #if article doesnt exist return
        if topic_name.nil?
          @document.topic_identifiers << TopicIdentifier.create(:name => ti)
          next

        #else article exists
        else
          @topic = Topic.find_by_name(topic_name)
          #check for topic
          if @topic && @topic.description
            @document.topic_identifiers << TopicIdentifier.create(:name => ti, :topic_id => @topic.id)
          elsif @topic
            #look up article on wikipedia
            full_topic = Topic.lookup_on_wiki(topic_name)
            next if full_topic.nil?
            #if it's a disambig page create identifier and throw disambig flag
            if full_topic[:article][:disambig]
              @new_ti = TopicIdentifier.create(:name => ti, :is_disambiguation => true)
              @document.topic_identifiers << @new_ti
              @ambiguous_terms << {:name => ti, :topic_id => @new_ti.id, :links => full_topic[:follow]}
            else
              #otherwise update the topic with new info and create identifier for it
              @topic.update_attributes(
                  :img_url => (full_topic[:article][:image][0] if full_topic[:article][:image]),
                  :description => (Document.clean_markup_from_desc(full_topic[:article][:description][0]) if full_topic[:article][:description]),
                  :blanked => full_topic[:article][:description][0]) #Iconv.conv("UTF-8//IGNORE", "US-ASCII", full_topic[:article][:description][0]))
              @document.topic_identifiers << TopicIdentifier.create(:name => ti, :topic_id => @topic.id)
              Cat.add_categories(full_topic[:article][:catlinks])
              @topic.build_q_and_a
            end
          else
            #create topic from wiki
            full_topic = Topic.lookup_on_wiki(topic_name)
            next if full_topic.nil?
            puts full_topic[:article][:name]
            #if it's a disambig page create identifier and throw disambig flag
            if full_topic[:article][:disambig]
              @new_ti = TopicIdentifier.create(:name => ti, :is_disambiguation => true)
              @document.topic_identifiers << @new_ti
              @ambiguous_terms << {:name => ti, :topic_id => @new_ti.id, :links => full_topic[:follow]}
            else
              #otherwise update the topic with new info and create identifier for it
              @topic = Topic.create(
                  :name => (full_topic[:article][:name] if full_topic[:article][:name]),
                  :img_url => (full_topic[:article][:image][0] if full_topic[:article][:image]),
                  :description => (Document.clean_markup_from_desc(full_topic[:article][:description][0]) if full_topic[:article][:description]),
                  :blanked => full_topic[:article][:description][0]) #Iconv.conv("UTF-8//IGNORE", "US-ASCII", full_topic[:article][:description][0]))
              @document.topic_identifiers << TopicIdentifier.create(:name => ti, :topic_id => @topic.id)
              Cat.add_categories(full_topic[:article][:catlinks])
              @topic.build_q_and_a
            end
          end
        end
      else
        @document.topic_identifiers << @topic_identifier
        next if @topic_identifier.topic_id.nil?  
        @topic = Topic.find_by_id(@topic_identifier.topic_id)
        #check if linked topic has full desc
        if @topic.description.nil?
          full_topic = Topic.lookup_on_wiki(@topic.name)
          ## HANDLE THIS EVENT
          next if full_topic.nil?
          
          #if it's a disambig page create identifier and throw disambig flag
          if full_topic[:article][:disambig]
            @topic_identifier.update_attribute(:is_disambiguation, true)
            @ambiguous_terms << {:name => ti, :topic_id => @topic_identifier.id, :links => full_topic[:follow]}
            next
          else
            #otherwise update the topic with new info and create identifier for it
            @topic.update_attributes(
                :img_url => (full_topic[:article][:image][0] if full_topic[:article][:image]),
                :description => (Document.clean_markup_from_desc(full_topic[:article][:description][0]) if full_topic[:article][:description]),
                :blanked => full_topic[:article][:description][0]) #Iconv.conv("UTF-8//IGNORE", "US-ASCII", full_topic[:article][:description][0]))
            Cat.add_categories(full_topic[:article][:catlinks])
            @topic.build_q_and_a
          end
        end
      end
    end
    return @ambiguous_terms
  end

  def self.clean_markup_from_desc(str)
    get_text = Scraper.define do
      process "p", :just_text => :text
      result :just_text
    end

    begin
      raw_text = get_text.scrape(str)
      raw_text.gsub! /\<[^>]*>\]/, ""
      raw_text.gsub! /\[[^]*]\]/, ""
      raw_text.gsub! /\([^)]*\)/, ""
      raw_text.gsub!(" ,", ",")
    rescue
      raw_text =  "ERROR!!"
    end

    return raw_text
  end 
  
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
    # GET /documents
  # GET /documents.xml
  def index
    @documents = Document.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @documents }
    end
  end

  # GET /documents/1
  # GET /documents/1.xml
  def show
    @document = Document.find(params[:id])
    @answers = {}
    @topic_identifiers = @document.topic_identifiers
    @topic_identifiers.each do |ti|
      if ti.topic.nil?
        @topic = Topic.create(:name => ti.name, :description => "", :blanked => "")
        ti.update_attribute(:topic_id, @topic.id)
      else
        @topic = ti.topic
      end      
      @answers[@topic.id] = ""

      @topic.answers.each do |answer|
        @answers[@topic.id] += "#{answer.name}\n"
      end      
    end
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @document }
    end
  end

  # GET /documents/new
  # GET /documents/new.xml
  def new

    @document = Document.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @document }
    end
  end

  # GET /documents/1/edit
  def edit
    @document = Document.find(params[:id])
  end

  # POST /documents
  # POST /documents.xml
  def create
    @document = Document.create!(params[:document])
    @ambiguous_terms = Document.parse_list(@document.id) unless @document.nil?
    @topic_identifiers = @document.topic_identifiers
    if !@ambiguous_terms.empty? && @document.save
      render :action => 'disambiguate'
    elsif @document.save
      redirect_to(@document, :notice => 'document was successfully created.')
    end
  end

  def update
    @document = Document.find(params[:id])

    respond_to do |format|
      if @document.update_attributes(params[:document])
        format.html { redirect_to(@document, :notice => 'document was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @document.errors, :status => :unprocessable_entity }
      end
    end
  end

  def disambiguate_term
    @topic = Topic.wiki_disambiguate(params[:link], params[:term_id])
    render :nothing => true
  end

  def reload_term
    Topic.wiki_disambiguate(Topic.wiki_page_name(params[:term]), params[:term_id])
    render :nothing => true
  end

  # DELETE /documents/1
  # DELETE /documents/1.xml
  def destroy
    @document = Document.find(params[:id])
    @document.destroy

    respond_to do |format|
      format.html { redirect_to(documents_url) }
      format.xml  { head :ok }
    end
  end

  ## THIS IS NOT A REAL METHOD!!! JUST A CSV EXPORT EXAMPLE ##
  def export_document_to_csv
    @document = Document.find_by_id(params[:id])
    return if @document.nil?

    csv_string_test = FasterCSV.generate do |csv|
      csv << ["term", "definition", "question", "incorrect answers"]

     @document.topic_identifiers.each do |ti|
        topic = Topic.find_by_id(ti.topic_id)
        answers = Answer.where("topic_id = ?",ti.topic_id)
        next if topic.nil? || topic.description.nil? || topic.description.length < 1

        row = [clean_markup_from_desc(ti.name), clean_markup_from_desc(topic.description), clean_markup_from_desc(topic.question)]
        unless answers.nil?
          answers.each do |a|
            row << clean_markup_from_desc(a.name)
          end
        end
        csv << row
      end
    end

    # send it to the browsah
    send_data csv_string_test,
              :type => 'text/csv; charset=iso-8859-1; header=present',
              :disposition => "attachment; filename=#{params[:file_name]}.csv"
  end

  private

  def clean_markup_from_desc(str)
    str.gsub!("\s{2,}", " ")
    str.gsub!(" .", ".")
    str.gsub!("\n","")
    return str
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_for(@document) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %><br /><br />

    <%= f.label :csv %><br />
    <%= f.text_area :csv %>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/documents/disambiguate.html.erb
<%= stylesheet_link_tag "disambiguate" %>

<% @ambiguous_terms.each do |term| %>
	<% form_tag({:controller => "documents", :action => "disambiguate_term"}, :remote => true) do %>
		<%= content_tag :div, :class => "container" do %>
			<br />
			<h2>Disambiguate: <%= term[:name] %></h2><br />
			<% term[:links].each do |link| %>
				<%= hidden_field_tag "doc_id", @document.id %>
				<%= hidden_field_tag "term_id", term[:topic_id] %>
				<%= radio_button_tag "link", link %> <%= link %>
				<br />
			<% end %>
			<br />
			<%= submit_tag "Update term" %>
			<br />
		<% end %>
	<% end %>
	<br /><br />
<% end %>
<%= button_to "Done", :action => "show", :id => @document.id %>

app/views/documents/disambiguate2.html.erb
<h3>Disambiguation</h3>
<br /><br />
<% @ambiguous_terms.each do |term| %>
  <%= form_for term, :remote => true do |form| %>
    <h3><%= term.name %></h3>
    <% puts "Here's yo LINKS, bro:" %>
  	<% puts term.links.to_json %>     
    <%= term.links.each do |link| %>
      <% puts "Here's yo link, bro:" %>
  	  <% puts link.to_json %> 
      <br><%= form.radio_button 'Link', link %> <%= link %> 
    <% end %>
    <%= form.submit %>  
  <% end %>
  <br /><br />
<% end %>

<br /><br />

<%= button_to "Done", :action => 'show', :id => @document.id %>

app/views/documents/edit.html.erb
<h1>Editing list</h1>

<%= render 'form' %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>



<% topic = Topic.find(ti.topic_id) %>
  <b><%= ti.name %> d:<%=ti.is_disambiguation%></b><br />
  <% next if topic.nil? %>
  <p>
    <%= topic.inspect %>
    <%  if topic.question %>
      <%= topic.question %>
    <% else %>
    <em>No question made for this topic</em>
    <% end %>

  </p>
  <ul>
    <% wrong = Answer.where("topic_id = ?", topic.id) %>
    <% wrong.each do |w| %>
    <li><%= w.name %></li>
    <%  end %>
  </ul>

app/views/documents/index.html.erb
<h1>Listing Docs</h1>

<table>
  <tr>
    <th>Doc Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @documents.each do |doc| %>
  <tr>
    <td><%= doc.name %></td>
    <td><%= link_to 'Show', doc %></td>
    <td><%= link_to 'Edit', edit_document_path(doc) %></td>
    <td><%= link_to 'Destroy', doc, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New List', new_document_path %>

app/views/documents/new.html.erb
<h1>New Document</h1>

<%= render 'form' %>

<%= link_to 'Back', documents_path %>

app/views/documents/new_show.html.erb
<p id="notice"><%= notice %></p>

<h2><%=@document.name%></h2>

<% @topic_identifiers.each do |ti| %>
  <div>
    <%= form_for topic do |form| %>
      
      <%= form.label :name %>
      <%= form.text_field :name %><br />

      <%= form.label ti.topic %>
      <%= form.text_field ti.topic %><br />

      <%= form.label :description %>
      <%= form.text_field :description %><br />

      <%= form.label :question %>
      <%= form.text_field :question %><br />     

      <%= form.label :question %>
      <%= form.text_field :question %><br />   

      <% puts "yo"  %>
      <!-- <%= form.label ti.question %> -->
      <!-- <%= form.text_field ti.question %><br /> -->

            
    <%end%>
  </div>
<%end%>





<p>
  <%=@document.csv%>
</p>
<% @topic_identifiers.each do |ti| %>
  <b><%= ti.name %> disambiguation:<%=ti.is_disambiguation%></b><br />
  <% next if ti.topic_id.nil? %>
  <% topic = Topic.find(ti.topic_id) %>
  <% next if topic.nil? %>
  <p>
    <%  if topic.question %>
      <%= topic.question %>
    <% else %>
    <em>No question made for this topic</em>
    <% end %>

  </p>
  <ul>
    <% wrong = Answer.where("topic_id = ?", topic.id) %>
    <% wrong.each do |w| %>
    <li><%= w.name %></li>
    <%  end %>
  </ul>
<%end%>

app/views/documents/show.html.erb
<%= javascript_include_tag "show" %>
<%= stylesheet_link_tag "show" %>

<p id="notice"><%= notice %></p>
<center><h1><%=@document.name%></h1></center>
<br /><hr /><br />
<% @topic_identifiers.each do |ti| %>
  <% next if ti.is_disambiguation %>
  <% @topic = ti.topic %>
    <%= form_for @topic, :remote => true do |form| %>
      <%= content_tag :div, :class => "container", :id => "div_" + @topic.id.to_s do %>
        <br />     
        <center><h1><%= "#{ti.name}" %></h1></center>
        <%= form.label "Wikipedia topic", :class => "label" %> 
        <%= form.text_field :name, :class => "field", :id => "title_" + @topic.id.to_s, :topic_id => "#{@topic.id}" %> 
        <%= link_to_function "Reload", "reloadTerm(#{@topic.id.to_s}, #{ti.id}, #{@document.id});" %>
        <br />

        <%= link_to "Original article", "http://www.wikipedia.org/wiki/#{@topic.name}", :target => "_blank", :id => "original_" + @topic.id.to_s %> or  
        <%= link_to "Wiki Search", "http://en.wikipedia.org/w/index.php?title=Special%3ASearch&search=#{@topic.name}&fulltext=Search&ns0=1&redirs=1&profile=advanced", :target => "_blank", :id => "wiki_search_" + @topic.id.to_s %>
        <br /><br />

        <%= form.label "Definition", :class => "label" %>
        <%= form.text_area :description, :rows=>8, :cols=>60, :class => "field", :id => "description_" + @topic.id.to_s, :topic_id => "#{@topic.id}" %>
        <br /><br />

        <%= form.label "Question", :class => "label" %>
        <%= form.text_area :question, :rows=>4, :cols=>60, :class => "field", :id => "question_" + @topic.id.to_s, :topic_id => "#{@topic.id}" %>
        <br /><br />

        <%= form.label "Answers", :class => "label" %>
        <%= text_area "answers", "text", :value => @answers[@topic.id], :rows=>10, :cols=>60, :class => "field", :id => "answers_" + @topic.id.to_s, :topic_id => "#{@topic.id}" %>
        <br /><br />

        <%= form_tag('/topics/' + @topic.id.to_s, :remote => true, :id => @topic.id.to_s) do %>
          <div><%= submit_tag 'Save', :class => "save", :id => @topic.id.to_s %></div>
        <% end %>
        <br />     
      <% end %>
      <br /><hr /><br />         
    <% end %>
<% end %>

app/views/documents/show_old.html.erb
<p id="notice"><%= notice %></p>

<h2><%=@document.name%></h2>
<p>
  <%=@document.csv%>
</p>
<% @topic_identifiers.each do |ti| %>
  <b><%= ti.name %> disambiguation:<%=ti.is_disambiguation%></b><br />
  <% next if ti.topic_id.nil? %>
  <% topic = Topic.find(ti.topic_id) %>
  <% next if topic.nil? %>
  <p>
    <%  if topic.question %>
      <%= topic.question %>
    <% else %>
    <em>No question made for this topic</em>
    <% end %>

  </p>
  <ul>
    <% wrong = Answer.where("topic_id = ?", topic.id) %>
    <% wrong.each do |w| %>
    <li><%= w.name %></li>
    <%  end %>
  </ul>
<%end%>